#!/usr/bin/env python3
"""
Synchronize agent rules across Claude Code, Cursor, and other AI tools.

This script:
1. Reads CLAUDE.md (canonical source) and .claude/rules/*.md
2. Generates AGENTS.md as a flat concatenation for non-Claude tools
3. Generates .cursor/rules/*.mdc wrappers that reference .shared-rules/

Usage:
    python scripts/sync_rules.py

The generated files (AGENTS.md) should be committed.
CLAUDE.md is hand-edited and IS the canonical source — do not overwrite it.
"""

import re
from pathlib import Path
import sys

# Project root
ROOT = Path(__file__).parent.parent

# Source files (canonical)
CLAUDE_MD = ROOT / "CLAUDE.md"
CLAUDE_RULES_DIR = ROOT / ".claude" / "rules"
SHARED_RULES = ROOT / ".shared-rules"

# Output files (generated)
AGENTS_MD = ROOT / "AGENTS.md"
CURSOR_RULES_DIR = ROOT / ".cursor" / "rules"

# Regex to strip YAML frontmatter (paths: directives are Claude Code-specific)
FRONTMATTER_RE = re.compile(r"\A---\n.*?---\n+", re.DOTALL)


def read_claude_md() -> str:
    """Read the canonical CLAUDE.md."""
    if not CLAUDE_MD.exists():
        print(f"Error: {CLAUDE_MD} does not exist")
        sys.exit(1)
    return CLAUDE_MD.read_text(encoding="utf-8")


def collect_claude_rules() -> list[tuple[str, str]]:
    """Collect all .md files from .claude/rules/, stripping frontmatter."""
    rules = []

    if not CLAUDE_RULES_DIR.exists():
        print(f"Warning: {CLAUDE_RULES_DIR} does not exist")
        return rules

    for path in sorted(CLAUDE_RULES_DIR.glob("*.md")):
        content = path.read_text(encoding="utf-8")
        # Strip YAML frontmatter (paths: directives are for Claude Code only)
        content = FRONTMATTER_RE.sub("", content)
        rules.append((path.name, content))

    return rules


def generate_agents_md(claude_content: str, rules: list[tuple[str, str]]) -> str:
    """Generate AGENTS.md from CLAUDE.md + .claude/rules/ content."""
    header = """\
<!-- AUTO-GENERATED from CLAUDE.md + .claude/rules/ — do not edit this file by hand. -->
<!-- Run scripts/sync_rules.py to regenerate. -->

"""

    sections = [claude_content]
    for filename, content in rules:
        sections.append(content)

    return header + "\n---\n\n".join(sections)


def generate_cursor_rules():
    """Generate .cursor/rules/*.mdc wrappers."""
    CURSOR_RULES_DIR.mkdir(parents=True, exist_ok=True)

    # Map shared rules to Cursor wrappers
    wrapper_configs = [
        ("coding-standards", "coding-standards.md", False),
        ("agent-workflow", "agent-workflow.md", True),  # Always apply
        ("project-organization", "project-organization.md", False),
    ]

    for rule_name, shared_file, always_apply in wrapper_configs:
        if not (SHARED_RULES / shared_file).exists():
            print(f"Warning: {SHARED_RULES / shared_file} does not exist, skipping")
            continue

        wrapper_content = f"""\
---
description: {rule_name.replace('-', ' ').title()}
globs:
alwaysApply: {str(always_apply).lower()}
---

@include ../../.shared-rules/{shared_file}
"""

        wrapper_path = CURSOR_RULES_DIR / f"{rule_name}.mdc"
        wrapper_path.write_text(wrapper_content, encoding="utf-8")
        print(f"Generated: {wrapper_path.relative_to(ROOT)}")


def main():
    """Main sync function."""
    print("Syncing agent rules...")
    print()

    # 1. Read canonical CLAUDE.md
    claude_content = read_claude_md()
    print(f"Read: {CLAUDE_MD.relative_to(ROOT)}")

    # 2. Collect .claude/rules/*.md (strip frontmatter for flat output)
    rules = collect_claude_rules()
    if rules:
        print(f"Found {len(rules)} rule files in .claude/rules/:")
        for filename, _ in rules:
            print(f"  - {filename}")
    else:
        print("No rule files found in .claude/rules/")
    print()

    # 3. Generate AGENTS.md
    agents_content = generate_agents_md(claude_content, rules)
    AGENTS_MD.write_text(agents_content, encoding="utf-8")
    print(f"Generated: {AGENTS_MD.relative_to(ROOT)}")

    # 4. Generate Cursor wrappers
    print()
    generate_cursor_rules()

    print()
    print("Done!")
    print()
    print("Next steps:")
    print("  - Commit AGENTS.md (auto-generated)")
    print("  - CLAUDE.md is the canonical source — edit it directly")
    print("  - .cursor/rules/ is gitignored (regenerate on clone)")


if __name__ == "__main__":
    main()
